### PR TITLE
Master

### PR DESCRIPTION
**Pull request by myParakeet**

### CODE REVIEW

**Comment by myParakeet** [comment]
Still getting the hang of GitHub. I think it will be better if I pull things individually - what do you think?

**Comment by Nicte** [comment]
Yeah I was thinking the same, how should we contribute? Pull request per change, or changes bundled together? (I'm hearthbot8899)

**Comment by Nicte** [comment]
Also, what do you think about lowering the big bonus fairy dragon gets?

if (card.name == CardDB.cardName.faeriedragon) return -25;

I think -25 may be a bit excesive?

**Comment by myParakeet** [comment]
Agreed and added. 

-Deadly shot needs a penalty so it's not wasted small, non-special minions - Do you want to try that?
-Something needs to be done about minions not being split on both sides of direwolf and flametongue - Do you want to try that?

**Comment by sliverfishes** [comment]
Yes separate pulls would be better.

Try to keep penalties in PenalityManager.cs because it's easier to find everything by using the card names instead of id's and cards can share code there too. I was thinking about removing the pentemplate like HB did but wanted to compare performance first...

I see lots of problems currently:
A cardvalue for hex/poly isn't going to solve the problem of it wanting to enrage a target before hex/poly'ing it and you removed the lowered penalties for priority/silence targets. What it really needs is extra penalty if there are any actions before it that target the same target.

Why is servertest123.zip updated? I'm tempted to remove many of the old irrelevant files...

What are you trying to solve with the no coin penalty? Isn't that just going to help allow coin+(auctioner||flamewaker) which would be pretty bad plays?

The doomsayer copy paste is a start but it needs to also sum up weapon attack and hero temp attack. Probably even better would be to just lower the value of boards that have doomsayer alive in getPlayfieldValue() for each of the behaviors.

The flame juggler stuff looks good. You can leave it in the pen file if you want.

**Comment by myParakeet** [comment]
**Hex/Poly**
- Removing the 'lowered penalty' for hex/poly on large minions fixes the problem of wanting to enrage first. No more advantage to buffing enemy minions prior to casting.
- I purposefully removed the 'lowered penalty' for poly/hex on a priority/silence target. The advantage of poly/hex on a priority/silence target should come from the boardvalue calculation itself or from the value of silencing one of those targets. If priority/silence minions are not getting targeted enough due to this change, we should fix it by upping the value of silencing those targets,- not by decreasing the value of poly/hex itself. Example: add bonus to getSilencePenality. 

**Server123.zip**
I cannot get rid of this change. If I delete it, it just comes back. It occurs automatically. Something github is doing behind the scenes. 

**no coin penalty**
The point was to not discourage using coin the cast a minion or spell that has a random effect. Example: coin + flamejuggler, coin + arcane missles, etc. 
Shouldn't avoiding coin + (auctioner||flamewaker) come from a cardvalue on coin? Either way, we shouldn't punish using coin to cast any card with a random effects. 

**pentemplate**
I like the current setup, but its up to you.

**Comment by sliverfishes** [comment]
A flat penalty for hex/poly won't do. It will still cause things like aoe -> enrage -> hex/poly now worth casting -> minion still on board instead of hex/poly -> aoe -> minion gone. I'm wrapping up things with the new mulligan code and then I'll pull in a couple hours.

**Comment by myParakeet** [comment]
I do not think that can happen - but I may be missing some details.

With the changes, there is no benefit to the board value for buffing an enemy minion before casting hex/poly. Therefore, simulations that cast hex/poly _first_ will result in higher board values. In your example, [hex/poly -> aoe -> minion death] is going to have a higher board value than [aoe -> enrage -> hex/poly] because the enemy has one less minion. 

Are you saying that it will not simulate casting hex/poly _first_ if the penalty value is greater than the gain from hex/poly? It was my understanding that it did do those calculations when deciding potential moves, but calculated them after the full turn was simulated. I think a penalty value of 500 can stop moves from being simulated, but I thought that was a 'special' hardcoded value.

**Comment by sliverfishes** [comment]
In those two hypothetical boards the one without the minion should be a higher value board but there's often fringe cases that aren't easily noticed, and there's also all the other boards that don't play poly/hex that have a chance of becoming the highest value board if they were already close in value.

**Comment by myParakeet** [comment]
I recommend dropping the 'reduced' penalties.

If a board has a higher value from not playing poly/hex and the penalty for poly/hex is reasonable, that other board _should_ be played. Bot should kill the 4/4 with its 5/5 minion and save poly/hex instead of casting poly/hex then killing. 

What kind of fringe cases do you mean? Unless I am missing something:
- If there is no reward for wasting resources to make a bigger target, then the bot will not favor those moves. 
- Unless the bot will not simulate casting poly/hex, moves that cast poly/hex first are going to be favorable. Exception: There may be some potential for random damage to occur prior to poly/hex when it shouldn't. Because the bot assumes worst case scenario for random damage, it will assume the poly/hex target does not die. It will therefore calculate no value from casting the random damage after poly/hex. However, it does value doing random action prior to other actions. It might make sense to keep using the database lookups you created. We still want to avoid poly/hexing a target that might die before casting poly/hex though. For example, if random damage will kill the target, we should not poly/hex first.

**Pull request merged**
