### PR TITLE
Master

### PR DESCRIPTION
**Pull request by myParakeet**
Only 'real' commit here is: "Add missing druid 'choose one' cards"

### CODE REVIEW

**Comment by myParakeet** [comment]
Everything is bogus commits I needed to get GitHub working, EXCEPT
**Add missing druid 'choose one' cards**

**Comment by Nicte** [comment]
One silly question (on how to use github basically). If I want to do a comment on a particular change (this one specifically: https://github.com/sliverfishes/silverfish/pull/3/commits/af834c103e006faadd3d77aab0245ee0d9e9b183), how should I do it? Add it to the pull request chain of comments, like now? or is there a way to comment on a specific change?

Basically, the link above refers to the changes we did on how to calculate the doomsayer logic. I am wondering if this bit:

`foreach (Minion mnn in p.ownMinions) totalAngr += mnn.Angr;`

Should take into account if the minion is ready to attack, in order to add its attack to the total count. Maybe we were attacking doomsayers without killing them because we are adding the attack of minions which are not ready to attack this turn?

Or am I missing something here?

**Comment by Photonious** [comment]
I found a typo in the Shaman Aggro mulligan file. 

https://github.com/sliverfishes/silverfish/blob/master/Deck%20Settings/Data/Shaman/Standard%20Aggro%20Shaman/_mulligan.txt

Line 48 has "LEX1_008" instead of "EX1_008".

**Comment by sliverfishes** [comment]
Those are not bogus commits, they are conflicts that you need to resolve with git resolve. After you resolve it all, please start cherry picking changes individually.

@Nicte - In order to comment on changes separately they need to be separate pull requests. In order to make them separate requests you have to make a new branch in your local repo, "cherry pick" the commits you want in the pull request to add them to your new branch, and then send a pull request for that branch. Each separate change needs to do all that.

The initial thought was readiness doesn't matter because if the test is true for the first minion that attacks then it will stay true for the rest and if its false then it will stay false on the boards that use spells/hero attacks first (you only need 1 board to do things right to become the best board), but there are some minions that nobody plays in current meta that can't attack unless certain conditions/silenced that we would overestimate.

**Comment by myParakeet** [comment]
They had to be resolved manually and the conflict resolution commited: https://githowto.com/resolving_conflicts

**Pull request closed without merging**
